//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOSSlowdown.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iOSSlowdown.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        internal static string AboutThisApp {
            get {
                return ResourceManager.GetString("AboutThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already own this app. Thank you!.
        /// </summary>
        internal static string AlreadyOwned {
            get {
                return ResourceManager.GetString("AlreadyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemocytometer Sidekick.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Feedback.
        /// </summary>
        internal static string AudioFeedback {
            get {
                return ResourceManager.GetString("AudioFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basophil.
        /// </summary>
        internal static string Basophil {
            get {
                return ResourceManager.GetString("Basophil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basophilic Band Cell.
        /// </summary>
        internal static string BasophilicBandCell {
            get {
                return ResourceManager.GetString("BasophilicBandCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basophilic Metamyelocyte.
        /// </summary>
        internal static string BasophilicMetamyelocyte {
            get {
                return ResourceManager.GetString("BasophilicMetamyelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing seems to be unavailable, please try again later..
        /// </summary>
        internal static string BillingNotAvailable {
            get {
                return ResourceManager.GetString("BillingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast.
        /// </summary>
        internal static string Blast {
            get {
                return ResourceManager.GetString("Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Cells.
        /// </summary>
        internal static string BloodCells {
            get {
                return ResourceManager.GetString("BloodCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Cell Counter Milestone.
        /// </summary>
        internal static string BloodCounterMilestone {
            get {
                return ResourceManager.GetString("BloodCounterMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Differential.
        /// </summary>
        internal static string BloodDifferential {
            get {
                return ResourceManager.GetString("BloodDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Blood Cell Counters.
        /// </summary>
        internal static string BloodDifferentialSorting {
            get {
                return ResourceManager.GetString("BloodDifferentialSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürker-Türk/Thoma.
        /// </summary>
        internal static string BurkerTurkThoma {
            get {
                return ResourceManager.GetString("BurkerTurkThoma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bürker-Türk/Thoma (Inner).
        /// </summary>
        internal static string BurkerTurkThomaInner {
            get {
                return ResourceManager.GetString("BurkerTurkThomaInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy!.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Name.
        /// </summary>
        internal static string CellName {
            get {
                return ResourceManager.GetString("CellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cells|cells/μL|cells/mL|cells/L|cells/mm³|cells/cm³.
        /// </summary>
        internal static string CellsUnitOptions {
            get {
                return ResourceManager.GetString("CellsUnitOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Type.
        /// </summary>
        internal static string CellType {
            get {
                return ResourceManager.GetString("CellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Chambers.
        /// </summary>
        internal static string ChamberCount {
            get {
                return ResourceManager.GetString("ChamberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber Depth.
        /// </summary>
        internal static string ChamberDepth {
            get {
                return ResourceManager.GetString("ChamberDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neubauer (standard): 100 μm.
        /// </summary>
        internal static string ChamberDepthHint {
            get {
                return ResourceManager.GetString("ChamberDepthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber Type.
        /// </summary>
        internal static string ChamberType {
            get {
                return ResourceManager.GetString("ChamberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app must be restarted to apply your changes..
        /// </summary>
        internal static string ChangesRestart {
            get {
                return ResourceManager.GetString("ChangesRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 Nicholas C. Bauer, Ph.D..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting counts!.
        /// </summary>
        internal static string CounterConflictWarning {
            get {
                return ResourceManager.GetString("CounterConflictWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Mode.
        /// </summary>
        internal static string CounterMode {
            get {
                return ResourceManager.GetString("CounterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Counter Value.
        /// </summary>
        internal static string CounterValue {
            get {
                return ResourceManager.GetString("CounterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: This app sends minimal data to Microsoft&apos;s AppCenter to notify me of serious problems (i.e., crashes)..
        /// </summary>
        internal static string CrashDataNotice {
            get {
                return ResourceManager.GetString("CrashDataNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Update Error.
        /// </summary>
        internal static string DatabaseUpdateError {
            get {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, there was a problem updating the database. Please use Feedback to report the problem so I can fix it. It may be a temporary problem though, so please try again..
        /// </summary>
        internal static string DatabaseUpdateErrorMessage {
            get {
                return ResourceManager.GetString("DatabaseUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string Dead {
            get {
                return ResourceManager.GetString("Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion is permanent. Are you sure you want to delete this measurement of {0} taken on {1}?.
        /// </summary>
        internal static string DeleteVerify {
            get {
                return ResourceManager.GetString("DeleteVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilution Factor.
        /// </summary>
        internal static string DilutionFactor {
            get {
                return ResourceManager.GetString("DilutionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Units.
        /// </summary>
        internal static string DisplayUnits {
            get {
                return ResourceManager.GetString("DisplayUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation. If you appreciate the new features, please support my work!.
        /// </summary>
        internal static string DonationRequest {
            get {
                return ResourceManager.GetString("DonationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eosinophil.
        /// </summary>
        internal static string Eosinophil {
            get {
                return ResourceManager.GetString("Eosinophil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eosinophilic Band Cell.
        /// </summary>
        internal static string EosinophilicBandCell {
            get {
                return ResourceManager.GetString("EosinophilicBandCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eosinophilic Metamyelocyte.
        /// </summary>
        internal static string EosinophilicMetamyelocyte {
            get {
                return ResourceManager.GetString("EosinophilicMetamyelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback / Help.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchs-Rosenthal.
        /// </summary>
        internal static string FuchsRosenthal {
            get {
                return ResourceManager.GetString("FuchsRosenthal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Options.
        /// </summary>
        internal static string GeneralOptions {
            get {
                return ResourceManager.GetString("GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the menu ≡ to get started!.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granular Lymphocyte.
        /// </summary>
        internal static string GranularLymphocyte {
            get {
                return ResourceManager.GetString("GranularLymphocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemocytometer.
        /// </summary>
        internal static string Hemocytometer {
            get {
                return ResourceManager.GetString("Hemocytometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I improve your experience with Hemocytometer Sidekick?.
        /// </summary>
        internal static string HowCanIImprove {
            get {
                return ResourceManager.GetString("HowCanIImprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Neubauer.
        /// </summary>
        internal static string ImprovedNeubauer {
            get {
                return ResourceManager.GetString("ImprovedNeubauer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Neubauer (Inner).
        /// </summary>
        internal static string ImprovedNeubauerInner {
            get {
                return ResourceManager.GetString("ImprovedNeubauerInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Normoblasts.
        /// </summary>
        internal static string IncludesNormoblasts {
            get {
                return ResourceManager.GetString("IncludesNormoblasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes Reticulocytes.
        /// </summary>
        internal static string IncludesReticulocytes {
            get {
                return ResourceManager.GetString("IncludesReticulocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wrote this app so that counting cells with a hemocytometer is quick and painless. I hope you find it useful!.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item appears to be unavailable. Please try again and report with Feedback if you keep seeing this..
        /// </summary>
        internal static string ItemNotAvailable {
            get {
                return ResourceManager.GetString("ItemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jessen.
        /// </summary>
        internal static string Jessen {
            get {
                return ResourceManager.GetString("Jessen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Result.
        /// </summary>
        internal static string LinkToResult {
            get {
                return ResourceManager.GetString("LinkToResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymphocyte.
        /// </summary>
        internal static string Lymphocyte {
            get {
                return ResourceManager.GetString("Lymphocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makler.
        /// </summary>
        internal static string Makler {
            get {
                return ResourceManager.GetString("Makler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malassez.
        /// </summary>
        internal static string Malassez {
            get {
                return ResourceManager.GetString("Malassez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrow Cells.
        /// </summary>
        internal static string MarrowCells {
            get {
                return ResourceManager.GetString("MarrowCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megakaryocyte.
        /// </summary>
        internal static string Megakaryocyte {
            get {
                return ResourceManager.GetString("Megakaryocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μm.
        /// </summary>
        internal static string Micrometers {
            get {
                return ResourceManager.GetString("Micrometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monocyte.
        /// </summary>
        internal static string Monocyte {
            get {
                return ResourceManager.GetString("Monocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemocytometer.org.
        /// </summary>
        internal static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myelocyte.
        /// </summary>
        internal static string Myelocyte {
            get {
                return ResourceManager.GetString("Myelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutrophil.
        /// </summary>
        internal static string Neutrophil {
            get {
                return ResourceManager.GetString("Neutrophil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutrophilic Band Cell.
        /// </summary>
        internal static string NeutrophilicBandCell {
            get {
                return ResourceManager.GetString("NeutrophilicBandCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutrophilic Metamyelocyte.
        /// </summary>
        internal static string NeutrophilicMetamyelocyte {
            get {
                return ResourceManager.GetString("NeutrophilicMetamyelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated framework, added Makler grid, blood cell counters can have custom ordering, customizable milestone for blood cells.
        /// </summary>
        internal static string NewFeatures {
            get {
                return ResourceManager.GetString("NewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results have been recorded.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normoblast.
        /// </summary>
        internal static string Normoblast {
            get {
                return ResourceManager.GetString("Normoblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — present; did you mean 0?.
        /// </summary>
        internal static string NullCounterWarning {
            get {
                return ResourceManager.GetString("NullCounterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment seems to be invalid, please try again..
        /// </summary>
        internal static string PaymentInvalid {
            get {
                return ResourceManager.GetString("PaymentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment does not seem to be enabled/allowed, please try again..
        /// </summary>
        internal static string PaymentNotAllowed {
            get {
                return ResourceManager.GetString("PaymentNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma Cell.
        /// </summary>
        internal static string Plasma {
            get {
                return ResourceManager.GetString("Plasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platelet.
        /// </summary>
        internal static string Platelet {
            get {
                return ResourceManager.GetString("Platelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prolymphocyte.
        /// </summary>
        internal static string Prolymphocyte {
            get {
                return ResourceManager.GetString("Prolymphocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promegakaryocyte.
        /// </summary>
        internal static string Promegakaryocyte {
            get {
                return ResourceManager.GetString("Promegakaryocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promonocyte.
        /// </summary>
        internal static string Promonocyte {
            get {
                return ResourceManager.GetString("Promonocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promyelocyte.
        /// </summary>
        internal static string Promyelocyte {
            get {
                return ResourceManager.GetString("Promyelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase cancelled..
        /// </summary>
        internal static string PurchaseCancelled {
            get {
                return ResourceManager.GetString("PurchaseCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Failed.
        /// </summary>
        internal static string PurchaseFailed {
            get {
                return ResourceManager.GetString("PurchaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purchase was not completed..
        /// </summary>
        internal static string PurchaseNotCompleted {
            get {
                return ResourceManager.GetString("PurchaseNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Pending.
        /// </summary>
        internal static string PurchasePending {
            get {
                return ResourceManager.GetString("PurchasePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Restore Failed.
        /// </summary>
        internal static string PurchaseRestoreFailed {
            get {
                return ResourceManager.GetString("PurchaseRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Success.
        /// </summary>
        internal static string PurchaseSuccess {
            get {
                return ResourceManager.GetString("PurchaseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase the product to enable deletion. Please support my work 🙂..
        /// </summary>
        internal static string PurchaseToDelete {
            get {
                return ResourceManager.GetString("PurchaseToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2 Donation.
        /// </summary>
        internal static string PurchaseVersion2 {
            get {
                return ResourceManager.GetString("PurchaseVersion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v3 Donation.
        /// </summary>
        internal static string PurchaseVersion3 {
            get {
                return ResourceManager.GetString("PurchaseVersion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v4 Donation.
        /// </summary>
        internal static string PurchaseVersion4 {
            get {
                return ResourceManager.GetString("PurchaseVersion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you finding this app useful? Please rate it to let others know! (Updating an old rating also helps.).
        /// </summary>
        internal static string RatingRequest {
            get {
                return ResourceManager.GetString("RatingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBC.
        /// </summary>
        internal static string RBC {
            get {
                return ResourceManager.GetString("RBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Purchases.
        /// </summary>
        internal static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this if you have recently reinstalled this app and had previously purchased it..
        /// </summary>
        internal static string RestorePurchasesExplanation {
            get {
                return ResourceManager.GetString("RestorePurchasesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore State Error.
        /// </summary>
        internal static string RestoreStateError {
            get {
                return ResourceManager.GetString("RestoreStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, there was a problem restoring your state. Your saved data is not affected. If this keeps happening, please report the problem with Feedback..
        /// </summary>
        internal static string RestoreStateErrorMessage {
            get {
                return ResourceManager.GetString("RestoreStateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an unsaved count. Would you like to resume or start fresh?.
        /// </summary>
        internal static string ResumeMessage {
            get {
                return ResourceManager.GetString("ResumeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume?.
        /// </summary>
        internal static string ResumeTitle {
            get {
                return ResourceManager.GetString("ResumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reticulocyte.
        /// </summary>
        internal static string Reticulocyte {
            get {
                return ResourceManager.GetString("Reticulocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Name.
        /// </summary>
        internal static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the service. Please try again later..
        /// </summary>
        internal static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Counter.
        /// </summary>
        internal static string SingleCounter {
            get {
                return ResourceManager.GetString("SingleCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiers-Levy.
        /// </summary>
        internal static string SpiersLevy {
            get {
                return ResourceManager.GetString("SpiersLevy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread the Word.
        /// </summary>
        internal static string SpreadTheWord {
            get {
                return ResourceManager.GetString("SpreadTheWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the app store seems to be unavailable. Try again later..
        /// </summary>
        internal static string StoreNotAvailable {
            get {
                return ResourceManager.GetString("StoreNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the store. Please check your internet connection..
        /// </summary>
        internal static string StoreUnableToConnect {
            get {
                return ResourceManager.GetString("StoreUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-press two to swap.
        /// </summary>
        internal static string SwapInstruction {
            get {
                return ResourceManager.GetString("SwapInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now own Hemocytometer Sidekick! Thank you for your support!.
        /// </summary>
        internal static string ThankYouForPurchase {
            get {
                return ResourceManager.GetString("ThankYouForPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the purchase is completed, use &quot;Restore Purchases&quot; in Settings. Thank you for your support!.
        /// </summary>
        internal static string ThankYouPending {
            get {
                return ResourceManager.GetString("ThankYouPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Counters.
        /// </summary>
        internal static string ThreeCounters {
            get {
                return ResourceManager.GetString("ThreeCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too dilute!.
        /// </summary>
        internal static string TooDilute {
            get {
                return ResourceManager.GetString("TooDilute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TranslationHelp {
            get {
                return ResourceManager.GetString("TranslationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} free uses left..
        /// </summary>
        internal static string TrialFreeUsesLeft {
            get {
                return ResourceManager.GetString("TrialFreeUsesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m glad you&apos;ve been finding this useful! Please support my work and get continued access by making a purchase..
        /// </summary>
        internal static string TrialPurchase {
            get {
                return ResourceManager.GetString("TrialPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Counters.
        /// </summary>
        internal static string TwoCounters {
            get {
                return ResourceManager.GetString("TwoCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |μL|mL|L.
        /// </summary>
        internal static string UnitOptions {
            get {
                return ResourceManager.GetString("UnitOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.
        /// </summary>
        internal static string Version2 {
            get {
                return ResourceManager.GetString("Version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 3.
        /// </summary>
        internal static string Version3 {
            get {
                return ResourceManager.GetString("Version3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 4.
        /// </summary>
        internal static string Version4 {
            get {
                return ResourceManager.GetString("Version4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viability.
        /// </summary>
        internal static string Viability {
            get {
                return ResourceManager.GetString("Viability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viable.
        /// </summary>
        internal static string Viable {
            get {
                return ResourceManager.GetString("Viable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Needed.
        /// </summary>
        internal static string VolumeNeeded {
            get {
                return ResourceManager.GetString("VolumeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBC.
        /// </summary>
        internal static string WBC {
            get {
                return ResourceManager.GetString("WBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
